@baseUrl=http://localhost:3000/api

@resourceName=cities

# cities

# @name getAllCities
GET {{baseUrl}}/{{resourceName}}

###
# @name getAllCitiesWithFilter
GET {{baseUrl}}/{{resourceName}}?_limit=10&_page=1